CREATE DATABASE db_clientes;

USE db_clientes;

CREATE TABLE Clientes(
	CLI_ID INT IDENTITY(1,1) PRIMARY KEY,
    CLI_NOME VARCHAR(50),
    CLI_DATANASCIMENTO DATE,
    CLI_ATIVO BIT
);

DECLARE @counter INT = 1;

WHILE @counter <= 20
BEGIN
    INSERT INTO Clientes (CLI_NOME, CLI_DATANASCIMENTO, CLI_ATIVO)
    SELECT 
        LEFT(NEWID(), 8) AS CLI_NOME,  
        DATEADD(DAY, ABS(CHECKSUM(NEWID())) % 36525, '1900-01-01') AS CLI_DATANASCIMENTO,  
        CAST(ABS(CHECKSUM(NEWID())) % 2 AS BIT) AS CLI_ATIVO;

    SET @counter = @counter + 1;
END;

SELECT * FROM Clientes;